[package]
name = "jge-tpl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
jge-core = { version = "0.1.0", path = "../jge-core" }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
nalgebra = "0.34.1"
